# Generated by Django 4.2 on 2023-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('Name', models.TextField(max_length=30)),
                ('Venue', models.TextField(max_length=1)),
                ('cordinator', models.CharField(max_length=25)),
                ('Discription', models.TextField(max_length=300)),
            ],
        ),
    ]
