# Generated by Django 4.2 on 2023-05-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Venue',
            new_name='Block',
        ),
    ]
