# Generated by Django 4.2 on 2023-05-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0002_rename_venue_event_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Block',
            field=models.CharField(max_length=1),
        ),
    ]
