# Generated by Django 4.2 on 2023-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0004_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cordinator',
            new_name='Cordinator',
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
