# Generated by Django 4.2 on 2023-05-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0005_rename_cordinator_event_cordinator_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Cordinator',
            new_name='cordinator',
        ),
    ]
