# Generated by Django 4.2 on 2023-05-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0006_rename_cordinator_event_cordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Block',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='A', max_length=1),
        ),
    ]
