# Generated by Django 4.2 on 2023-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0007_alter_event_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Block',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
