# Generated by Django 4.2 on 2023-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0008_alter_event_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('Name', models.TextField(max_length=30)),
                ('SOR', models.DateTimeField(verbose_name='Start_of_Registration')),
                ('EOR', models.DateTimeField(verbose_name='End_of_Registration')),
                ('Stream', models.TextField(max_length=100)),
                ('CTC', models.BigIntegerField()),
                ('Profile', models.CharField(max_length=20)),
                ('Cordinator', models.CharField(max_length=25)),
                ('Discription', models.TextField(max_length=500)),
            ],
        ),
    ]
