# Generated by Django 3.1.5 on 2023-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0010_alter_placement_ctc'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=122, verbose_name='event_name')),
                ('first_name', models.CharField(max_length=122, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=122, verbose_name='last_name')),
                ('email', models.EmailField(max_length=125, verbose_name='email')),
                ('block', models.CharField(max_length=120, verbose_name='block name')),
                ('branch', models.CharField(max_length=120, verbose_name='branch')),
                ('enrollment_number', models.CharField(max_length=120, verbose_name='enrollment_number')),
                ('phone_number', models.CharField(max_length=10, verbose_name='phone_number')),
                ('university', models.CharField(max_length=150)),
            ],
        ),
    ]
