# Generated by Django 4.2.1 on 2023-06-10 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0011_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{1,10}$')]),
        ),
    ]
