# Generated by Django 4.2.1 on 2023-06-10 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0012_alter_user_registration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='block',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[A-C]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='event_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
